name: Workflow
on:
  workflow_dispatch:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Show machine info
      run: |
        id
        df -h
        docker image ls
        docker container ls
        docker container ls --all
    - name: Install prerequisites
      run: |
        sudo apt-get install \
          moreutils \

    - name: Set environment
      run: |
        echo "IMAGE_NAME=$(make --question docker_image_name)" >> $GITHUB_ENV
    - name: Download cache from Docker Hub
      # Here we assume that latest release have common layers that should speed up our build
      run: |
        docker manifest inspect $IMAGE_NAME:latest &> /dev/null && \
        docker pull $IMAGE_NAME:latest
    - name: Build
      run: |
        DOCKER_CACHE_FROM=$IMAGE_NAME:latest \
        make docker_image
    - name: Test
      run: make check
    - name: Clean
      run: make clean

